<a href="https://colab.research.google.com/github/Joydeep75/SHALA2020/blob/master/JG_Assignment_1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [14]:
import numpy as np

a1 = np.arange(15).reshape(3,5)
b1 = np.arange(15).reshape(3,5)

a = np.random.rand(3,5)
b = np.random.rand(3,5)

print(a1)
print(b1)

print(a) 
print(b)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.46174906 0.03978639 0.35347303 0.39785483 0.26461485]
 [0.97386919 0.4648059  0.5498373  0.44983158 0.57039695]
 [0.13528316 0.08854301 0.65891731 0.5888842  0.61702791]]
[[0.2481868  0.99668724 0.79817031 0.28843961 0.89966619]
 [0.46499324 0.71076636 0.7571529  0.91500997 0.56884089]
 [0.95770976 0.9944497  0.74531541 0.09479969 0.25132834]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all non-negative integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [9]:
c = np.arange(100)

d = np.zeros((3,3))
# d = np.zeros(3) # or np.zeros(3, dtype=np.float) OR np.zeros(3, dtype=np.float32)

print(c)
print(d)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [10]:
e = [[1,2,3],[4,5,6],[7,8,9]]
e = np.array(e)
print(e)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [11]:
f = np.ones((5,5))
print(f)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
g = np.eye(5)
print(g)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $c^\prime$ and print **YES** when the shapes of $c$ and $c^\prime$ are same. Otherwise print **NO**.

In [0]:
h = c.reshape(10, 10)
h
c1 = h.flatten()

if c.shape == c1.shape:
  print('YES')
else:
  print('NO')


YES


Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [36]:
A = np.random.rand(2,10,5)
print(A.shape)

A1 = A.transpose()
# print(A1)
print(A1.shape)

A2 = A1.reshape(5, 2, 10)
print(A2.shape)

A3 = A.transpose().reshape(5, 2, 10)
print(A3.shape)

(2, 10, 5)
(5, 10, 2)
(5, 2, 10)
(5, 2, 10)


In [18]:
d = np.array([[1,2,30],[4,50,6], [7,8,9]])
print(d)

idx_col_max = np.argmax(d, axis = 0)
d, idx_col_max, d[np.array([idx_col_max])]

[[ 1  2 30]
 [ 4 50  6]
 [ 7  8  9]]


You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [30]:
import numpy as np

np.random.seed(0)
X = np.random.rand(10,5)

print(X)

# for column: axis = 0 and for row: axis = 1 

# Minimum value and index where it occured, for each column
print(np.min(X, 0), np.argmin(X, 0))

# Maximum value and the index where it occured, for each column
print(np.max(X,axis = 0), np.argmax(X, axis = 0)) 

# Minimum value and index where it occured, for each row
print(np.min(X, 1), np.argmin(X, 1))
# Maximum value and index where it occured, for each row
print(np.max(X, axis = 1), np.argmax(X, axis =1))

# Minimum value and index where it occured, for the entire matrix
print(np.min(X), np.argmin(X))

# Maximum value and index where it occured, for the entire matrix
print(np.max(X), np.argmax(X))

# Note:
# # Maximum value and the index where it occured, for each column
# idx_col_max = np.argmax(X, axis=0) # axis=0 for column. This will give the index of the maximum value taking all the column value
# X, idx_col_max, X[idx_col_max]

# # idx_row_max = np.argmax(X, axis=1) # axis =1 for row. This will give the index of the maximum value taking all the row value
# X, idx_row, idx_col



[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]
 [0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898 ]
 [0.6176355  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672]
 [0.67063787 0.21038256 0.1289263  0.31542835 0.36371077]]
[0.0871293  0.0202184  0.1289263  0.06022547 0.0187898 ] [3 3 9 8 6]
[0.97861834 0.79915856 0.94466892 0.96366276 0.87001215] [4 4 5 1 3]
[0.4236548  0.38344152 0.07103606 0.0202184  0.11827443 0.14335329
 0.0187898  0.61209572 0.06022547 0.1289263 ] [4 4 4 1 4 1 4 1 3 2]
[0.71518937 0.96366276 0.92559664 0.87001215 0.97861834 0.94466892
 0.77423369 0.94374808 0.6976312  0.67063787] [1 3 3 4 0 2 1 3 2 0]
0.018789800

Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

In [32]:
# Mean of each row and column
print(np.mean(X, axis =1), np.mean(X, axis = 0))

# Standard deviation of each row and column
print(np.std(X, axis = 0), np.std(X, axis = 1))

# Mean of the entire matrix
print(np.mean(X))

# Standard deviation of entire matrix
print(np.std(X))

[0.56706085 0.66447172 0.57705944 0.51762729 0.62761197 0.5328907
 0.41643268 0.69444672 0.44423265 0.33781717] [0.56044382 0.46781457 0.62009909 0.64025127 0.40121685]
[0.24687647 0.25752158 0.22948615 0.28054144 0.26584905] [0.09445299 0.23322986 0.29189733 0.38052993 0.30431633 0.26338419
 0.25841437 0.12727959 0.23169975 0.18537332]
0.5379651182755409
0.27226582292177587


Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [54]:
np.random.seed(3)
Y = np.random.rand(10,10)
print(Y)

# Determinant
print('Determinent of Y = {}'.format(np.linalg.det(Y)))

# Rank of the matrix
print('Rank of Y = {}'.format(np.linalg.matrix_rank(Y)))

# Diagonal Elements
print('Type1 : Diagonal Elements of Y are = {}'.format(Y.diagonal()))
# OR
print('Type2: Diagonal Elements of Y are = {}'.format(np.diag(Y)))

# Trace
print('Trace of Y = {}'.format(np.trace(Y)))

# Eigen values
print('First Way : Eigen Value of Y are = {}'.format(np.linalg.eigvals(Y)))

Y_eigen_value, Y_eigen_vector = np.linalg.eig(Y)
print('2nd Way : Eigen Value of Y are = {}'.format(Y_eigen_value))

# Matrices obtained after Singular Value Decomposition
u, sigma, v_transpose = np.linalg.svd(Y)

print('u of Y = \n{}'.format(u))
print('v_transpose of Y = \n{}'.format(v_transpose))
print('Singular Value of Y = \n{}'.format(sigma))

# print('\033[1;37;44m u of Y = {} \n'.format(u))
# print('\034[1;37;44m sigma of Y = {} \n'.format(sigma))
# print('\035[1;37;44m v_transpose of Y = {} \n'.format(v_transpose))

# Inverse if exists, otherwise Pseudo-Inverse -- Manually
if (np.linalg.det(Y)) != 0:
  inv_matrix_Y = np.linalg.inv(Y)
else:
  psudo_inv_matrix_Y = np.linalg.pinv(Y)

print('Inverse if exists, otherwise Pseudo-Inverse {}'.format(np.linalg.pinv(Y)))

# Inverse if exists, otherwise Pseudo-Inverse -- In a single line
print('Inverse if exists, otherwise Pseudo-Inverse {}'.format(np.linalg.pinv(Y)))

# Multiplication  𝑌  with  𝑋 
print('Multiplication  𝑌  with  𝑋 {}'.format(np.matmul(Y, X)))

# Element-wise multiplication of  𝑌  and its inverse(or pseudo-inverse)
print('Element-wise multiplication of 𝑌  and its inverse(or pseudo-inverse) {}'.format(np.linalg.pinv(Y)))


[[0.5507979  0.70814782 0.29090474 0.51082761 0.89294695 0.89629309
  0.12558531 0.20724288 0.0514672  0.44080984]
 [0.02987621 0.45683322 0.64914405 0.27848728 0.6762549  0.59086282
  0.02398188 0.55885409 0.25925245 0.4151012 ]
 [0.28352508 0.69313792 0.44045372 0.15686774 0.54464902 0.78031476
  0.30636353 0.22195788 0.38797126 0.93638365]
 [0.97599542 0.67238368 0.90283411 0.84575087 0.37799404 0.09221701
  0.6534109  0.55784076 0.36156476 0.2250545 ]
 [0.40651992 0.46894025 0.26923558 0.29179277 0.4576864  0.86053391
  0.5862529  0.28348786 0.27797751 0.45462208]
 [0.20541034 0.20137871 0.51403506 0.08722937 0.48358553 0.36217621
  0.70768662 0.74674622 0.69109292 0.68918041]
 [0.37360012 0.6681348  0.33984866 0.57279387 0.32580716 0.44514505
  0.06152893 0.24267542 0.97160261 0.2305842 ]
 [0.69147751 0.65047686 0.72393914 0.47508861 0.59666377 0.06696942
  0.07256214 0.19897603 0.151861   0.10010434]
 [0.12929386 0.55327773 0.18781482 0.95210124 0.68161178 0.54101967
  0.7071806 

## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [0]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"



In [0]:
# Read the dataset, 
df = pd.read_csv(file_url)

In [10]:
# Find the Shape (row, col) of the dataFrame
df.shape

(1309, 14)

In [11]:
# Get the first few rows
df.head()

pclass  survived  ...   body                        home.dest
0       1         1  ...    NaN                     St Louis, MO
1       1         1  ...    NaN  Montreal, PQ / Chesterville, ON
2       1         0  ...    NaN  Montreal, PQ / Chesterville, ON
3       1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4       1         0  ...    NaN  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

In [16]:
# Check if there is any missing values in the dataframe or not
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     1309 non-null   int64  
 1   survived   1309 non-null   int64  
 2   name       1309 non-null   object 
 3   sex        1309 non-null   object 
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64  
 6   parch      1309 non-null   int64  
 7   ticket     1309 non-null   object 
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object 
 10  embarked   1307 non-null   object 
 11  boat       486 non-null    object 
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object 
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB


In [17]:
# See the structure of the dataframe
df.describe()

pclass     survived  ...         fare        body
count  1309.000000  1309.000000  ...  1308.000000  121.000000
mean      2.294882     0.381971  ...    33.295479  160.809917
std       0.837836     0.486055  ...    51.758668   97.696922
min       1.000000     0.000000  ...     0.000000    1.000000
25%       2.000000     0.000000  ...     7.895800   72.000000
50%       3.000000     0.000000  ...    14.454200  155.000000
75%       3.000000     1.000000  ...    31.275000  256.000000
max       3.000000     1.000000  ...   512.329200  328.000000

[8 rows x 7 columns]

In [20]:
# This will tell us the total number of NaN in the data columnwise
# https://towardsdatascience.com/the-tale-of-missing-values-in-python-c96beb0e8a9d
df.isnull().sum()

pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

In [0]:
# If the missing value isn’t identified as NaN , 
# then we have to first convert or replace such non NaN entry with a NaN. - If 
# we want to perform some statistics on the column.

# The following code will replace values of zero with NaN in the column 
# named column_name of our data_name.
df['age'].replace(0, np.nan, inplace = True)
df['fare'].replace(0, np.nan, implace = True)

### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---



In [15]:
titanic_data_new = pd.get_dummies(df[['sex', 'embarked', 'pclass']])
titanic_data_new.head()

pclass  sex_female  sex_male  embarked_C  embarked_Q  embarked_S
0       1           1         0           0           0           1
1       1           0         1           0           0           1
2       1           1         0           0           0           1
3       1           0         1           0           0           1
4       1           1         0           0           0           1



---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



In [21]:
mean_age = df['age'].mean()
mean_fare = df['fare'].mean()

titanic_data_new['age'] = df['age'].fillna(mean_age)
titanic_data_new['fare'] = df['fare'].fillna(mean_fare)

# Chek that of the columns got added or not
titanic_data_new.head()

pclass  sex_female  sex_male  ...  embarked_S    age      fare
0       1           1         0  ...           1  29.00  211.3375
1       1           0         1  ...           1   0.92  151.5500
2       1           1         0  ...           1   2.00  151.5500
3       1           0         1  ...           1  30.00  151.5500
4       1           1         0  ...           1  25.00  151.5500

[5 rows x 8 columns]

###Normalization


---



1. Normalize the columns which have numerical data



---





---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.